name: I only smoke when i drink

on:
  schedule:
    - cron: "0 0 */3 * *"
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  frontend:
    name: Build OpenList front-end
    runs-on: ubuntu-latest
    outputs:
      web_version: ${{ steps.version.outputs.web_version }}
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: latest

      - name: Clone OpenList Front-End
        shell: bash
        run: git clone --depth 1 https://github.com/OpenListTeam/OpenList-Frontend.git frontend-src

      - name: Set up pnpm
        uses: pnpm/action-setup@master
        with:
          package_json_file: frontend-src/package.json

      - name: Build OpenList Front-End
        shell: bash
        run: |
          set -euo pipefail
          cd frontend-src
          pnpm install --frozen-lockfile
          pnpm build

      - name: Get front-end version
        id: version
        shell: bash
        run: echo "web_version=$(git -C frontend-src describe --long --tags --always)" >> "$GITHUB_OUTPUT"

      - name: Upload front-end
        uses: actions/upload-artifact@main
        with:
          name: openlist-frontend
          path: frontend-src/dist/
          if-no-files-found: error
          retention-days: 1

  backend:
    name: Build ${{ matrix.openlist_nickname }}
    needs: frontend
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - openlist_nickname: linux-glibc-amd64v4
            goamd64: v4
          - openlist_nickname: linux-glibc-amd64v3
            goamd64: v3
          - openlist_nickname: linux-glibc-amd64v2
            goamd64: v2
          - openlist_nickname: linux-glibc-amd64v1
            goamd64: v1
          - openlist_nickname: linux-glibc-amd64
          - openlist_nickname: linux-musl-amd64
            cgo_enabled: "0"
          - openlist_nickname: linux-musl-arm64
            goos: linux
            goarch: arm64
            cgo_enabled: "0"
          - openlist_nickname: darwin-arm64
            goos: darwin
            goarch: arm64
            cgo_enabled: "0"
          - openlist_nickname: windows-amd64.exe
            goos: windows
            goarch: amd64
            cgo_enabled: "0"
    steps:
      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: stable

      - name: Clone OpenList Back-End
        shell: bash
        run: git clone --depth 1 https://github.com/OpenListTeam/OpenList.git backend-src

      - name: Download front-end
        uses: actions/download-artifact@main
        with:
          name: openlist-frontend
          path: backend-src/public/dist

      - name: Build OpenList Back-End
        shell: bash
        env:
          CGO_ENABLED: ${{ matrix.cgo_enabled }}
          GOARCH: ${{ matrix.goarch }}
          GOOS: ${{ matrix.goos }}
          GOAMD64: ${{ matrix.goamd64 }}
          OUTPUT_NAME: ${{ matrix.openlist_nickname }}
          WEB_VERSION: ${{ needs.frontend.outputs.web_version }}
        run: |
          set -euo pipefail
          cd backend-src

          builtAt="$(date +'%F %T %z')"
          goVersion=$(go version | sed 's/go version //')
          gitAuthor=$(git show -s --format='format:%aN <%ae>' HEAD)
          gitCommit=$(git log --pretty=format:"%h" -1)
          version=$(git describe --long --tags --dirty --always)
          ldflags="-w -s \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.BuiltAt=$builtAt' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.GoVersion=$goVersion' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.GitAuthor=$gitAuthor' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.GitCommit=$gitCommit' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.Version=$version' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.WebVersion=$WEB_VERSION'"

          go build -ldflags "$ldflags" -o "openlist-$OUTPUT_NAME" .

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: OpenList
          files: dist/openlist-*
          body: |
            # OpenList binary
            - With high performance made by MoAEIOU & GitHub Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  openwrt:
    name: Build for ${{ matrix.patch_arch }}
    needs: release
    runs-on: ubuntu-latest
    env:
      project_name: "luci-app-oplist"
    strategy:
      fail-fast: true
      matrix:
        include:
          - patch_arch: "x86_64"
            sdk_arch: "x86-64"
            openlist_nickname: "linux-musl-amd64"
          - patch_arch: "aarch64_generic"
            sdk_arch: "rockchip-armv8"
            openlist_nickname: "linux-musl-arm64"
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: ${{ env.project_name }}

      - name: Get Version
        id: get_version
        shell: bash
        run: |
          cd ${{ env.project_name }}
          VERSION=$(grep -E "^PKG_VERSION[[:space:]]*:=" Makefile | sed -E 's/.*:=[[:space:]]*//' | tr -d '[:space:]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Preparing build environment
        uses: moaeiou/moaeiou/actions/build-env@main

      - name: Prepare SDK
        id: sdk
        uses: moaeiou/moaeiou/actions/prepare-sdk@main
        with:
          sdk_arch: ${{ matrix.sdk_arch }}

      - name: Download OpenList binary
        uses: actions/download-artifact@main
        with:
          name: binary-openlist-${{ matrix.openlist_nickname }}
          path: openlist-binary

      - name: Preparation before compilation
        shell: bash
        run: |
          mv ${{ env.project_name }} ${{ steps.sdk.outputs.sdk_dir }}/package/
          cd ${{ steps.sdk.outputs.sdk_dir }}/package/${{ env.project_name }}/
          if [ "${{ matrix.patch_arch }}" != "x86_64" ]; then
            sed -i 's/x86_64/${{ matrix.patch_arch }}/g' ./Makefile
          fi
          cd root/usr/bin/
          rm -f DONOTREMOVE
          install -m 0755 \
            "$GITHUB_WORKSPACE/openlist-binary/openlist-${{ matrix.openlist_nickname }}" \
            ./openlist
          cd ../../etc/openlist
          rm DONOTREMOVE

      - name: Build for OpenWrt
        shell: bash
        run: |
          cd ${{ steps.sdk.outputs.sdk_dir }}
          make package/${{ env.project_name }}/compile V=s -j$(nproc)

      - name: Rename compilation files
        shell: bash
        run: |
          mv ${{ steps.sdk.outputs.sdk_dir }}/bin/packages/*/base/luci-app*.apk $GITHUB_WORKSPACE/luci-app-oplist-${{ steps.get_version.outputs.version }}-${{ matrix.patch_arch }}.apk

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: |
            ${{ steps.sdk.outputs.sdk_dir }}/bin/packages/*/base/luci-i18n-oplist-*.apk
            ${{ github.workspace }}/luci-app-oplist-*.apk
          body: |
            # 📝 Release Note
            - Fixes and improvements
            # ⚠️ Breaking Changes
            - Back up `/etc/openlist` before upgrading.
            - Delete `/etc/openlist/config.json` and restart OpenList to regenerate the configuration.
            - Keep `/etc/openlist/data.db`, otherwise all OpenList data will be lost.
            - If you encounter any problems, please open an issue.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
