name: I only smoke when i drink

on:
  schedule:
    - cron: "10 0 */1 * *"
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  OpenList:
    name: Build for ${{ matrix.openlist_nickname }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - tag: "GOAMD64=v4"
            openlist_nickname: "linux-amd64v4-glibc"
          - tag: "GOAMD64=v3"
            openlist_nickname: "linux-amd64v3-glibc"
          - tag: "GOAMD64=v2"
            openlist_nickname: "linux-amd64v2-glibc"
          - tag: "GOAMD64=v1"
            openlist_nickname: "linux-amd64v1-glibc"
          - tag: ""
            openlist_nickname: "linux-amd64-glibc"
          - tag: "CGO_ENABLED=0"
            openlist_nickname: "linux-amd64-musl"
          - tag: "GOARCH=arm64"
            openlist_nickname: "linux-arm64-musl"
          - tag: "GOOS=darwin GOARCH=arm64"
            openlist_nickname: "darwin-arm64"
          - tag: "GOOS=windows GOARCH=amd64"
            openlist_nickname: "windows-amd64.exe"
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: useless/

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: latest

      - name: Clone OpenList Front-End
        shell: bash
        run: |
          git clone --depth 1 https://github.com/OpenListTeam/OpenList-Frontend.git frontend-src

      - name: Set up pnpm
        uses: pnpm/action-setup@master
        with:
          package_json_file: frontend-src/package.json

      - name: Build OpenList Front-End
        shell: bash
        run: |
          cd frontend-src
          pnpm install
          pnpm build

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: "stable"

      - name: Build OpenList Back-End
        shell: bash
        run: |
          git clone --depth 1 https://github.com/OpenListTeam/OpenList.git backend-src
          cd backend-src
          bash build.sh dev web

          builtAt="$(date +'%F %T %z')"
          goVersion=$(go version | sed 's/go version //')
          gitAuthor=$(git show -s --format='format:%aN <%ae>' HEAD)
          gitCommit=$(git log --pretty=format:"%h" -1)
          version=$(git describe --long --tags --dirty --always)
          webVersion=$(curl -s --max-time 5 "https://api.github.com/repos/OpenListTeam/OpenList-Frontend/releases/latest" -L | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed 's/^v//')
          if [ -z "$webVersion" ]; then
              exit 1
          fi
          ldflags="-w -s \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.BuiltAt=$builtAt' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.GoVersion=$goVersion' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.GitAuthor=$gitAuthor' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.GitCommit=$gitCommit' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.Version=$version' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.WebVersion=$webVersion'"

          ${{ matrix.tag }} go build -ldflags "$ldflags" -o openlist .
          chmod +x openlist
          mv ./openlist ${{ github.workspace }}/openlist-${{ matrix.openlist_nickname }}

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: openlist
          files: ${{ github.workspace }}/openlist-${{ matrix.openlist_nickname }}
          body: |
            # ⚙ OpenList
            High performance build binary kernel
            ## 📏 Filename Rule
            `openlist-archoptimization-LibC`

            For example: `openlist-amd64v4-glibc`
            ## Mirrored at <https://867678.xyz/doc/Mirror>
            ## Made by
            MoAEIOU & GitHub Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  OpenWrt:
    name: Build for openwrt-${{ matrix.patch_arch }}
    needs: OpenList
    runs-on: ubuntu-latest
    env:
      project_name: "luci-app-oplist"
    strategy:
      fail-fast: true
      matrix:
        include:
          - patch_arch: "x86_64"
            sdk_arch: "x86-64"
            openlist_nickname: "linux-amd64-musl"
          - patch_arch: "aarch64_generic"
            sdk_arch: "rockchip-armv8"
            openlist_nickname: "linux-arm64-musl"
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: ${{ env.project_name }}

      - name: Get Version
        id: get_version
        shell: bash
        run: |
          cd ${{ env.project_name }}
          VERSION=$(grep -E "^PKG_VERSION[[:space:]]*:=" Makefile | sed -E 's/.*:=[[:space:]]*//' | tr -d '[:space:]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Preparing build environment
        uses: moaeiou/moaeiou/actions/build-env@main

      - name: Prepare SDK
        id: sdk
        uses: moaeiou/moaeiou/actions/prepare-sdk@main
        with:
          sdk_arch: ${{ matrix.sdk_arch }}

      - name: Preparation before compilation
        shell: bash
        run: |
          mv ${{ env.project_name }} ${{ steps.sdk.outputs.sdk_dir }}/package/
          cd ${{ steps.sdk.outputs.sdk_dir }}/package/${{ env.project_name }}/
          if [ "${{ matrix.patch_arch }}" != "x86_64" ]; then
            sed -i 's/x86_64/${{ matrix.patch_arch }}/g' ./Makefile
          fi
          cd root/usr/bin/
          rm -f DONOTREMOVE
          wget -O openlist https://github.com/morouter/luci-app-oplist/releases/download/openlist/openlist-${{ matrix.openlist_nickname }}
          chmod +x ./openlist
          cd ../../etc/openlist
          rm DONOTREMOVE

      - name: Build for OpenWrt
        shell: bash
        run: |
          cd ${{ steps.sdk.outputs.sdk_dir }}
          make package/${{ env.project_name }}/compile V=s -j$(nproc)

      - name: Rename compilation files
        shell: bash
        run: |
          mv ${{ steps.sdk.outputs.sdk_dir }}/bin/packages/*/base/luci-app*.apk $GITHUB_WORKSPACE/luci-app-oplist-${{ steps.get_version.outputs.version }}-${{ matrix.patch_arch }}.apk

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: |
            ${{ steps.sdk.outputs.sdk_dir }}/bin/packages/*/base/luci-i18n-oplist-*.apk
            ${{ github.workspace }}/luci-app-oplist-*.apk
          body: |
            # 📝 Release Note
            - Fixes and improvements
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
