name: I only smoke when i drink

on:
  schedule:
    - cron: '0 0 */3 * *'
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Build for ${{ matrix.openlist_nickname }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tags: "GOAMD64=v4"
            target: "linux-amd64"
            openlist_nickname: "linux-glibc-amd64v4"
          - tags: "GOAMD64=v3"
            target: "linux-amd64"
            openlist_nickname: "linux-glibc-amd64v3"
          - tags: "GOAMD64=v2"
            target: "linux-amd64"
            openlist_nickname: "linux-glibc-amd64v2"
          - tags: "GOAMD64=v1"
            openlist_nickname: "linux-glibc-amd64v1"
          - tags: ""
            target: "linux-amd64"
            openlist_nickname: "linux-glibc-amd64"
          - tags: "CGO_ENABLED=0"
            target: "linux-amd64-musl"
            openlist_nickname: "linux-musl-amd64"
          - tags: "GOARCH=arm64"
            target: "linux-arm64-musl"
            openlist_nickname: "linux-musl-arm64"
          - tags: "GOOS=darwin GOARCH=arm64"
            target: "darwin-arm64"
            openlist_nickname: "darwin-arm64"
          - tags: "GOOS=windows GOARCH=amd64"
            target: "windows-amd64"
            openlist_nickname: "windows-amd64.exe"

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: useless/

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: latest

      - name: Set up pnpm
        uses: pnpm/action-setup@master
        with:
          version: latest

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: "stable"

      - name: Build!
        id: cgo-action
        uses: OpenListTeam/cgo-actions@v1
        with:
          dir: '.'
          tags: ${{ matrix.tags }}
          targets: ${{ matrix.targets }}
          packages: '.'
          flags: -ldflags=-w -s
          static-link-for-musl: true
          musl-base-url: https://github.com/OpenListTeam/musl-compilers/releases/latest/download
          musl-target-format: $os-$arch-$musl
          out-dir: $GITHUB_WORKSPACE
          output: openlist-${{ matrix.openlist_nickname }}

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: OpenList
          files: ${{ github.workspace }}/openlist-${{ matrix.openlist_nickname }}
          body: |
            # OpenList binary
            - With high performance made by MoAEIOU & GitHub Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
