name: I only smoke when i drink

on:
  schedule:
    - cron: "0 0 */3 * *"
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Build for ${{ matrix.openlist_nickname }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: "GOAMD64=v4"
            openlist_nickname: "linux-glibc-amd64v4"
          - tag: "GOAMD64=v3"
            openlist_nickname: "linux-glibc-amd64v3"
          - tag: "GOAMD64=v2"
            openlist_nickname: "linux-glibc-amd64v2"
          - tag: "GOAMD64=v1"
            openlist_nickname: "linux-glibc-amd64v1"
          - tag: ""
            openlist_nickname: "linux-glibc-amd64"
          - tag: "CGO_ENABLED=0"
            openlist_nickname: "linux-musl-amd64"
          - tag: "GOARCH=arm64"
            openlist_nickname: "linux-musl-arm64"
          - tag: "GOOS=darwin GOARCH=arm64"
            openlist_nickname: "darwin-arm64"
          - tag: "GOOS=windows GOARCH=amd64"
            openlist_nickname: "windows-amd64.exe"

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: useless/

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: latest

      - name: Clone OpenList Front-End
        shell: bash
        run: |
          git clone --depth 1 https://github.com/OpenListTeam/OpenList-Frontend.git frontend-src

      - name: Set up pnpm
        uses: pnpm/action-setup@master
        with:
          package_json_file: frontend-src/package.json
      
      - name: Build OpenList Front-End
        shell: bash
        run: |
          cd frontend-src
          pnpm install
          pnpm build
      
      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: "stable"

      - name: Build OpenList Back-End
        shell: bash
        run: |
          git clone --depth 1 https://github.com/OpenListTeam/OpenList.git backend-src
          cd backend-src
          bash build.sh dev web

          builtAt="$(date +'%F %T %z')"
          goVersion=$(go version | sed 's/go version //')
          gitAuthor=$(git show -s --format='format:%aN <%ae>' HEAD)
          gitCommit=$(git log --pretty=format:"%h" -1)
          version=$(git describe --long --tags --dirty --always)
          webVersion=$(curl -s --max-time 5 "https://api.github.com/repos/OpenListTeam/OpenList-Frontend/releases/latest" -L | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed 's/^v//')
          if [ -z "$webVersion" ]; then
              exit 1
          fi
          ldflags="-w -s \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.BuiltAt=$builtAt' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.GoVersion=$goVersion' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.GitAuthor=$gitAuthor' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.GitCommit=$gitCommit' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.Version=$version' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.WebVersion=$webVersion'"

          ${{ matrix.tag }} go build -ldflags "$ldflags" -o openlist .
          chmod +x openlist
          mv ./openlist ${{ github.workspace }}/openlist-${{ matrix.openlist_nickname }}

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: OpenList
          files: ${{ github.workspace }}/openlist-${{ matrix.openlist_nickname }}
          body: |
            # OpenList binary
            - With high performance made by MoAEIOU & GitHub Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
